### PR TITLE
Remove some weird rectangles in tracklist

### PR DESCRIPTION
**Pull request by whyredow**
before:
image
after:
Screenshot 2022-04-03 135357

### CODE REVIEW

**Comment by rlaphoenix** [comment]
I dont know if this is a full solution as the issue seems to also be the alignment of the headers. For example look at `Plays` its definitely off. Same with the Time icon, but not the # or `Title`.

**Comment by whyredow** [comment]
Probably fixed?

**Comment by whyredow** [comment]
image

**Comment by rlaphoenix** [comment]
Thanks a ton for your help and effort, but, I have superseded this pull request with https://github.com/williamckha/spicetify-fluent/pull/59

I will close this as while your pull request does 'fix' it, it's doing a slightly more hacky solution in comparison to my pull request. If you find any issues feel free to bring it up in that pull request and we can collaborate on adding any extra commits on that one.

**Pull request closed without merging**
